---
name: Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT_NAME: whattheduck
  BUILD_DIR: dist/spa

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # ---------- build ----------
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: "Install dependencies"
        run: |
          npm install -g @quasar/cli
          npm install
      - name: "Build"
        run: |
          quasar build
      # ---------- publish ----------
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ${{ env.BUILD_DIR }} --project-name=${{ env.PROJECT_NAME }}
