---
name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # ---------- build ----------
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: "Install dependencies"
        run: |
          npm install -g @quasar/cli
          npm install
      - name: "Build"
        run: |
          quasar build
      # ---------- publish ----------
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID}}
          projectName: whattheduck
          directory: dist/spa
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
